### PR TITLE
Update google_api_auth.py

### PR DESCRIPTION
**Pull request by skandix**
need to use tools.run_flow, since they've changed, that you can pipe in argument's to the credentials variable, if not able to authenticate with a local web browser. "--noauth_local_webserver"

### CODE REVIEW

**Comment by martinp** [comment]
Please fix the style mistakes reported by Travis. :-)

**Comment by skandix** [comment]
there, fixed.. only needed 
'from oauth2client import tools'

**Comment by martinp** [comment]
Great! Do you think you can rebase and squash it all into one commit also?

**Comment by skandix** [comment]
just remove all the prev branches, and make a new patch branch, with that one commit that did build ?
if i understood it correctly .... ?

**Comment by martinp** [comment]
That would work, but you can also use rebase: https://help.github.com/articles/about-git-rebase/

**Comment by martinp** [comment]
Merged manually: e98729ef23c45dca6b18e412f7475e6f89ef6195. Thanks!

**Pull request closed without merging**
